pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/ssparser/demojenkins.git' 
            }
        }
        
        stage('Build') {
            steps {
               echo "build" // Maven build command
            }
        }
        
        stage('Test') {
            steps {
               echo "test"
            }
        }

        stage('Deploy') {
            steps {
               echo "delploy"
            }
        }
    }
}
