pipeline {
    agent any
    
    tools {
        git 'Default'
        maven 'Maven'

    }
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ssparser/demojenkins.git'
            }
        }
        
        stage('Build') {
            steps {
                sh 'echo "Build step"'
                 sh 'mvn clean package'
            }
        }

        stage('Test') {
            steps {
                sh 'echo "Running tests"'
                sh 'mvn test'  
                junit '**/target/surefire-reports/*.xml'  
            }
        }
        
    }
    
    post {
        success {
            echo 'Pipeline succeeded! Deploying artifacts...'
        }
        failure {
            echo 'Pipeline failed! Sending notifications...'
        }
    }
}

