pipeline {
    agent any
    
    
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/ssparser/demojenkins.git' 
            }
        }
        
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package' // Maven build command
            }
        }
        
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        
        // Add more stages as needed, such as deploying to a server
        
        stage('Deploy') {
            steps {
                sh 'echo "Deploying the application"' // Example deployment step
                // Add your deployment script or commands here
            }
        }
    }
}
